### ISSUE TITLE
upscaledb does not compile with boost 1.66

### ISSUE THREAD

**Issue by Znurre** [cruppstahl/upscaledb#109]
```
In file included from ./3page_manager/page_manager.h:32:0,
                 from ./4env/env_local.h:32,
                 from ./3btree/btree_node_proxy.h:37,
                 from 2page/page.cc:28:
./2worker/worker.h:84:3: error: invalid use of template-name ‘boost::asio::strand’ without an argument list
   boost::asio::strand strand;
   ^~~~~
./2worker/worker.h:84:3: note: class template argument deduction is only available with -std=c++1z or -std=gnu++1z
In file included from /usr/include/boost/asio.hpp:123:0,
                 from ./2worker/worker.h:28,
                 from ./3page_manager/page_manager.h:32,
                 from ./4env/env_local.h:32,
                 from ./3btree/btree_node_proxy.h:37,
                 from 2page/page.cc:28:
/usr/include/boost/asio/strand.hpp:29:7: note: ‘template<class Executor> class boost::asio::strand’ declared here
 class strand
       ^~~~~~
In file included from ./3page_manager/page_manager.h:32:0,
                 from ./4env/env_local.h:32,
                 from ./3btree/btree_node_proxy.h:37,
                 from 2page/page.cc:28:
./2worker/worker.h: In constructor ‘upscaledb::WorkerPool::WorkerPool(size_t)’:
./2worker/worker.h:57:25: error: class ‘upscaledb::WorkerPool’ does not have any field named ‘strand’
     : working(service), strand(service) {
                         ^~~~~~
./2worker/worker.h: In member function ‘void upscaledb::WorkerPool::enqueue(F&)’:
./2worker/worker.h:65:5: error: ‘strand’ was not declared in this scope
     strand.post(f);
     ^~~~~~
./2worker/worker.h:65:5: note: suggested alternative:
In file included from /usr/include/boost/asio.hpp:123:0,
                 from ./2worker/worker.h:28,
                 from ./3page_manager/page_manager.h:32,
                 from ./4env/env_local.h:32,
                 from ./3btree/btree_node_proxy.h:37,
                 from 2page/page.cc:28:
/usr/include/boost/asio/strand.hpp:29:7: note:   ‘boost::asio::strand’
 class strand
       ^~~~~~
  CXX      3blob_manager/blob_manager_inmem.lo
make[3]: *** [Makefile:975: 2page/page.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from 3changeset/changeset.cc:19:0:
./2worker/worker.h:84:3: error: invalid use of template-name ‘boost::asio::strand’ without an argument list
   boost::asio::strand strand;
   ^~~~~
./2worker/worker.h:84:3: note: class template argument deduction is only available with -std=c++1z or -std=gnu++1z
In file included from /usr/include/boost/asio.hpp:123:0,
                 from ./2worker/worker.h:28,
                 from 3changeset/changeset.cc:19:
/usr/include/boost/asio/strand.hpp:29:7: note: ‘template<class Executor> class boost::asio::strand’ declared here
 class strand
       ^~~~~~
In file included from 3changeset/changeset.cc:19:0:
./2worker/worker.h: In constructor ‘upscaledb::WorkerPool::WorkerPool(size_t)’:
./2worker/worker.h:57:25: error: class ‘upscaledb::WorkerPool’ does not have any field named ‘strand’
     : working(service), strand(service) {
                         ^~~~~~
./2worker/worker.h: In member function ‘void upscaledb::WorkerPool::enqueue(F&)’:
./2worker/worker.h:65:5: error: ‘strand’ was not declared in this scope
     strand.post(f);
     ^~~~~~
./2worker/worker.h:65:5: note: suggested alternative:
In file included from /usr/include/boost/asio.hpp:123:0,
                 from ./2worker/worker.h:28,
                 from 3changeset/changeset.cc:19:
/usr/include/boost/asio/strand.hpp:29:7: note:   ‘boost::asio::strand’
 class strand
       ^~~~~~

```

**Comment by Znurre** [comment]
I created a PR for this https://github.com/cruppstahl/upscaledb/pull/110

**Comment by cruppstahl** [comment]
Merged, thank you
