### ISSUE TITLE
Failed to build with boost 1.33.1

### ISSUE THREAD

**Issue by likema** [cruppstahl/upscaledb#17]
- CentOS 5.9 x86_64
- boost: 1.33.1 is installed by yum.
  <pre>
  hamsterdb.cc:1191: error: no matching function for call to 'boost::detail::thread::scoped_lockboost::mutex::scoped_lock()'
  /usr/include/boost/thread/detail/lock.hpp:68: note: candidates are: boost::detail::thread::scoped_lock<Mutex>::scoped_lock(Mutex&, bool) [with Mutex = boost::mutex]
  /usr/include/boost/thread/detail/lock.hpp:64: note:                 boost::detail::thread::scoped_lockboost::mutex::scoped_lock(const boost::detail::thread::scoped_lockboost::mutex&)
  /usr/include/boost/noncopyable.hpp: In member function 'boost::detail::thread::scoped_lockboost::mutex& boost::detail::thread::scoped_lockboost::mutex::operator=(const boost::detail::thread::scoped_lockboost::mutex&)':
  /usr/include/boost/noncopyable.hpp:28: error: 'const boost::noncopyable_::noncopyable& boost::noncopyable_::noncopyable::operator=(const boost::noncopyable_::noncopyable&)' is private
  /usr/include/boost/thread/detail/lock.hpp:64: error: within this context
  /usr/include/boost/thread/detail/lock.hpp:64: error: non-static reference member 'boost::mutex& boost::detail::thread::scoped_lockboost::mutex::m_mutex', can't use default assignment operator
  </pre>
